# machine-written by `memoryschema deploy register` — do not hand-edit
[deployment]
project = "fractal"
repo_url = "https://github.com/shehzadqayum/fractal.git"
subtree_prefix = "pip @ v0.1.2"
scopes = ["working"]
schema_version = 5
branch = "deployments/fractal"
module_commit = "b27a6bc3bc04843b2fc9dbcb399e748dc494078c"
consumer_commit = "c30df2169ea159e28a529e610271fabd80a87fe0"
registered_at = "2026-07-14"
note = ""
