# machine-written by `memoryschema deploy register` — do not hand-edit
[deployment]
project = "helios"
repo_url = "https://github.com/shehzadqayum/helios.git"
subtree_prefix = "pip @ v0.2.0"
scopes = ["working"]
schema_version = 5
branch = "deployments/helios"
module_commit = "bc784f1fc6a739d6b67840fe75d36221d2dfae00"
consumer_commit = "84ea9f57351d55523dcb75c2261a3649a6db2797"
registered_at = "2026-07-14"
note = ""
